package worldcup

// TeamFlags maps canonical team names (as used in Entries) to flag emoji.
var TeamFlags = map[string]string{
	"Algeria":      "🇩🇿",
	"Argentina":    "🇦🇷",
	"Australia":    "🇦🇺",
	"Austria":      "🇦🇹",
	"Belgium":      "🇧🇪",
	"Bosnia":       "🇧🇦",
	"Brazil":       "🇧🇷",
	"Cabo Verde":   "🇨🇻",
	"Canada":       "🇨🇦",
	"Czechia":      "🇨🇿",
	"Colombia":     "🇨🇴",
	"Congo DR":     "🇨🇩",
	"Croatia":      "🇭🇷",
	"Curacao":      "🇨🇼",
	"Ecuador":      "🇪🇨",
	"Egypt":        "🇪🇬",
	"England":      "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
	"France":       "🇫🇷",
	"Germany":      "🇩🇪",
	"Ghana":        "🇬🇭",
	"Haiti":        "🇭🇹",
	"Iran":         "🇮🇷",
	"Iraq":         "🇮🇶",
	"Ivory Coast":  "🇨🇮",
	"Japan":        "🇯🇵",
	"Jordan":       "🇯🇴",
	"Mexico":       "🇲🇽",
	"Morocco":      "🇲🇦",
	"Netherlands":  "🇳🇱",
	"New Zealand":  "🇳🇿",
	"Norway":       "🇳🇴",
	"Panama":       "🇵🇦",
	"Paraguay":     "🇵🇾",
	"Portugal":     "🇵🇹",
	"Qatar":        "🇶🇦",
	"Saudi Arabia": "🇸🇦",
	"Scotland":     "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
	"Senegal":      "🇸🇳",
	"South Africa": "🇿🇦",
	"South Korea":  "🇰🇷",
	"Spain":        "🇪🇸",
	"Sweden":       "🇸🇪",
	"Switzerland":  "🇨🇭",
	"Tunisia":      "🇹🇳",
	"Turkey":       "🇹🇷",
	"Uruguay":      "🇺🇾",
	"USA":          "🇺🇸",
	"Uzbekistan":   "🇺🇿",
}
